### PR TITLE
So, finally I can start  tot work on the presentation. Here is the initi...

### PR DESCRIPTION
**Pull request by MateiVidican**
...al version of the presentation. Please give me some hints about what should I add to the presentation.

### CODE REVIEW

**Comment by skobls** [comment]
It tells me that since `HEAD` was merged into `master`, it is safe to delete `HEAD`. Well, let's try...

**Comment by MateiVidican** [comment]
I've merged those branches because for the moment we don't need 2 of them. I hope it's not a problem.

**Comment by skobls** [comment]
No problem, I am new to Git, therefore I am not sure in what I am doing :)

**Comment by MateiVidican** [comment]
I am not an expert too :)), so we learn while we are working.

**Pull request merged**
